优化调度器实时数据入库失败的debug流程
jewforice/l2 pull request #20
Opened 2022-03-20 14:44 UTC by jewforice

1. 需求链接
    https://trello.com/c/SPweoT0X
    2. 由于没有找到可以满足指定调度需求的库，所以还是继续使用apscheduler，只是将mt5_only和mt5+yfinance的拉取数据函数进行了分离，希望可以减少出错的机会
    3. logger_create默认按照日期分文件，方便定位日志；默认存放在logs目录下

2022-03-21 14:13 UTC, jhezjkp requested changes

2022-03-21 15:34 UTC, jewforice commented on libs/commons.py
> +        handler = logging.FileHandler('logs/'+name+datetime.now().strftime('%Y-%m-%d')+".txt")
已修改

2022-03-21 15:34 UTC, jewforice commented on libs/fetcher.py
> +    symbols = Symbol.select()
已修改

2022-03-21 15:34 UTC, jewforice commented
1. 修复了fetcher.update_realtime_data中，如果yfinance传入的start和end是带有时分秒的话，会导致无法拉取数据的问题
    2. 按照CR中的建议，使用TimedRotatingFileHandler来实现日志文件的按天分文件。当前只保存最近30天的文件。
    3. 安好CR中的建议，在fetcher.update_realtime_data中新增skip_symbol作为参数。当调
度器传入待跳过的symbol时，不去拉取该symbol的数据。以更优雅的方式实现在非交易时段不拉
取指定symbol的数据。

2022-03-21 16:15 UTC, jewforice commented
又发现了一个坑，yf_tz.localize对datetime.now()是不生效的，要写成datetime.now(yf_tz).date()……

2022-03-22 02:02 UTC, jhezjkp approved these changes
good job.

2022-03-22 02:03 UTC, merged